### ISSUE TITLE
SSL: UNSUPPORTED_PROTOCOL

### ISSUE THREAD

**Issue by feedb** [dirkjanm/PrivExchange#1] opened 2019-01-22 11:49 UTC
Traceback (most recent call last):
  File "privexchange.py", line 213, in <module>
    main()
  File "privexchange.py", line 137, in main
    session.request("POST", ews_url, POST_BODY % attacker_url, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:726)

**Comment by dirkjanm** [comment] 2019-01-22 14:06
Which python version and OS is this on? Most likely the issue is with supported protocols/ciphers.

**Comment by lean0x2F** [comment] 2019-01-22 19:38
The same happened to us when using Kali linux. If `curl https://exchange.domain/` throws an error, then it's an openssl problem. Try changing its config to use TLS 1.0 by default.

**Comment by feedb** [comment] 2019-01-23 03:50
thanks. fixed.
next error:
ERROR: Server returned HTTP 500: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidServerVersion</faultcode><faultstring xml:lang="ru-RU">The specified server version is invalid.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidServerVersion</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The specified server version is invalid.</e:Message></detail></s:Fault></s:Body></s:Envelope>

**Comment by dirkjanm** [comment] 2019-01-23 07:38
You may have to slightly change the exchange version in the SOAP body as specified in #2 , depending on which Exchange version you are talking to.

**Comment by dirkjanm** [comment] 2019-02-07 19:47
It would be nice to know what fixed this exactly for other people with this issue, but since this was resolved I'm closing this one.

**Closed as completed by dirkjanm** 2019-02-07 19:47 UTC
